## numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,6,12,13]],np.int64)

In [3]:
myarr

array([[ 3,  6, 12, 13]])

In [4]:
myarr[0,1]

np.int64(6)

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,1]=45
myarr

array([[ 3, 45, 12, 13]])

# array creation: conversion from other python structures

In [11]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [12]:
listarray.dtype

dtype('int64')

In [13]:
listarray.shape

(3, 3)

In [14]:
np.array({22,33,44})

array({33, 44, 22}, dtype=object)

In [16]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype


dtype('float64')

In [19]:
zeros.shape

(2, 5)

In [20]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lspace=np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [23]:
emp=np.empty((4,6))
emp

array([[4.67296746e-307, 1.69121096e-306, 2.22522461e-306,
        1.89146896e-307, 7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 1.37962320e-306, 1.29060871e-306,
        2.22518251e-306, 1.33511969e-306, 1.78022342e-306],
       [1.05700345e-307, 3.11525958e-307, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.29062229e-306, 1.24610383e-306, 6.89804132e-307,
        1.69121096e-306, 8.34449382e-308, 8.34402698e-308]])

In [24]:
emp_like=np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [26]:
ide.shape

(45, 45)

In [27]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
p=arr.reshape(3,33)
p

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr=arr.ravel()

In [33]:
arr.shape

(99,)

In [34]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [35]:
ar=np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
ar.sum(axis=0)

array([12, 15, 18])

In [38]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [39]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
ar.flat

In [41]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [42]:
ar.ndim

2

In [43]:
ar.size

9

In [44]:
ar.nbytes

72

In [46]:
one=np.array([1,3,4,634,2])
one.argmax()

np.int64(3)

In [47]:
one.argmin()

np.int64(0)

In [48]:
one.argsort()

array([0, 4, 1, 2, 3])

In [50]:
p=ar.argsort()
p

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [51]:
ar.argmin()

np.int64(0)

In [52]:
ar.argmax()

np.int64(8)

In [53]:
ar.argmax(axis=0)

array([2, 2, 2])

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
ar.argmax(axis=1)

array([2, 2, 2])

In [56]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [57]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [58]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [62]:
ar2=np.array([[1,2,1],
            [4,0,6],
            [15,2,0]])

In [63]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [22, 10,  9]])

In [64]:
[324,654]+[543,654]

[324, 654, 543, 654]

In [65]:
ar*ar2

array([[  1,   4,   3],
       [ 16,   0,  36],
       [105,  16,   0]])

In [66]:
ar/ar2

C:\Users\roy68\AppData\Local\Temp\ipykernel_14924\2166607628.py:1: RuntimeWarning: divide by zero encountered in divide
  ar/ar2


array([[1.        , 1.        , 3.        ],
       [1.        ,        inf, 1.        ],
       [0.46666667, 4.        ,        inf]])

In [67]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [68]:
ar.sum()

np.int64(45)

In [69]:
ar.min()

np.int64(1)

In [70]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
np.where(ar>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [72]:
np.count_nonzero(ar)

np.int64(9)

In [73]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [74]:
ar[1,2]=0

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [76]:
import sys

In [78]:
py_ar=[0,4,55,2]

In [82]:
np_ar=np.array(py_ar)
np_ar

array([ 0,  4, 55,  2])

In [80]:
sys.getsizeof(1)*len(py_ar)

112

In [81]:
np_ar.itemsize*np_ar.size

32